name: clang-format Check

# Trigger this workflow on pull requests to the repository
on:
  pull_request:
    branches:
      - main  # Adjust as needed for other branches

jobs:
  clang-format:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install clang-format
    - name: Install clang-format
      run: sudo apt-get install clang-format -y

    # Step 3: Check file permissions
    - name: List files and permissions
      run: ls -l

    # Step 4: Make clang-checker.sh executable
    - name: Make clang-checker.sh executable
      run: chmod +x ./clang-checker.sh

    # Step 5: Verify permissions again
    - name: Verify permissions
      run: ls -l ./clang-checker.sh

    # Step 6: Run the clang-checker.sh script
    - name: Run clang-checker.sh
      run: bash ./clang-checker.sh
